pipeline {
    agent any

    environment {
    SVC_ACCOUNT_KEY = credentials('terraform-auth')
  }
     
    stages {
            
            
		stage('Set creds') {
            steps {
              
                sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./google-compute-engine/jenkins.json'
		            sh 'pwd'
		    sh 'cd google-compute-engine'
                       
               
            }
        }
	
	stage('Auth-Project') {
	 steps {
		 dir('google-compute-engine')
    
        sh 'gcloud auth activate-service-account faheem@mi-uat-lab.iam.gserviceaccount.com --key-file=jenkins.json'
    }
    }
 	 
	stage('Create Instance') {
	 steps {
    
    sh 'gcloud compute instances create webhost3 --zone=us-central1-a'
        
    }
    }
    
    	
    
    
  
    
   }
}
}
